[package]
name = "server"
edition.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
chrono = { version = "0.4.45", default-features = false, features = ["clock", "serde", "std"] }
jsonwebtoken = { version = "11.1.0", features = ["rust_crypto"] }
protocol = { version = "0.1.0", path = "../protocol" }
reqwest = { version = "0.13.5", default-features = false, features = ["json", "rustls"] }
rusqlite = { version = "0.40.2", features = ["bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "signal", "net", "time"] }
toml = "1.1.6"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"

[[bin]]
name = "kidtime-server"
path = "src/main.rs"

[dev-dependencies]
base64 = "0.23.1"
http-body-util = "0.1.5"
rsa = "0.9.10"
tower = { version = "0.5.3", features = ["util"] }
